### ISSUE TITLE
data-0x39b770 

### ISSUE THREAD

**Issue by sp4rta** [Ascope-Team/write-ups-2018#1]
What is the offset of 0x39b770? and %2$s?

**Comment by sp4rta** [comment]
Hackcon-2018/Simple Yet Elegent_pwn_150/

**Comment by Neolex-Security** [comment]
I searched for a stack leak address so i tried 1 2 3 until one of the leak was in the stack,  2 was on the stack
When i found the leak address in the stack i compared it with the libc base : 
0x39b770(offset) = leak - libc_base

**Comment by sp4rta** [comment]
ok, thanks! XD
